<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<img src='<?php echo $this->getViewFileUrl('images/zip-logo.svg'); ?>' alt="paypal logo">
<div class="breaker"></div>
<div class="zip-text">
own it now, up to 6 months interest free 
<a href="<?= $block->escapeUrl('#') ?>" class="zip-link">learn more</a>
</div>