<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<div class="product-faq-container">
  <div class="product-faq__links">
    <a href="<?= $block->escapeUrl('#') ?>" class="product-faq__link">
      <span><?= __("Product Support") ?></span>
    </a>
    <a href="<?= $block->escapeUrl('#') ?>" class="product-faq__link">
      <span><?= __("FAQ") ?></span>
    </a>
    <a href="<?= $block->escapeUrl('#') ?>" class="product-faq__link">
      <span><?= __("Our Buyers Guide") ?></span>
    </a>
  </div>
</div>
</div>
