<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View\Description*/
?>

<div class="product-descriptions">
    <ul class="product-descriptions__list">
        <li>Intel Core i7-10700F</li>
        <li>Intel H410</li>
        <li>WHITE</li>
        <li>NVIDIA MSI GeForce RTX 2060 SUPER 8GB AERO ITX GDDR6</li>
        <li>SO-DIMM 16GB (16GB x 1) DDR4 2666MHz</li>
        <li>2 total slots (64GB Max)</li>
        <li>512GB (1 x 512GB) M.2 NVMe PCIe GEN3x4 SSD 2TB (2.5) 5400RPM</li>
        <li>Gaming Keyboard GK30 + Gaming Mouse GM11</li>
        <li>3.5 HDD (0/0), 2.5 HDD/SSD(1/0), M.2 (1/0)</li>
        <li>Intel WGI219Vethernet (10/100/1000M)</li>
        <li>AX200 (WIFI 6)+BT5.1</li>
        <li>PSU 330W</li>
        <li>Fan Cooler</li>
    </ul>
</div>

<div class="product-descriptions">
    <div class="product-description__specs">
        <div class="product-description__spec">
            <div class="product-description__spec--name">CPU</div>
            <div class="product-description__spec--value">N/A</div>
        </div>
        <div class="product-description__spec">
            <div class="product-description__spec--name">Featured</div>
            <div class="product-description__spec--value">N/A</div>
        </div>
        <div class="product-description__spec">
            <div class="product-description__spec--name">I/O Ports</div>
            <div class="product-description__spec--value">N/A</div>
        </div>
    </div>
</div>


<script>
    document.querySelector('.product-container').addEventListener('click', function(e) {

        const isBtn = e.target.matches("[data-product-link]");
        const isSubmit = e.target.matches('[type=submit]')
        if (!isBtn) {
            return
        }

        console.log(e.target.dataset.productLink)
        if (e.target.dataset.productLink !== "0") {
            document.querySelector("#product-options-wrapper").style.visibility = 'hidden'
            document.querySelector(".product-contact").classList.add('pd-t');
        } else {
            document.querySelector("#product-options-wrapper").style.visibility = ''
            document.querySelector(".product-contact").classList.remove('pd-t');
        }
        e.preventDefault();
        const descriptions = [...document.querySelectorAll('.product-descriptions')]
        descriptions.forEach((el) => el.classList.remove('active'));
        descriptions[e.target.dataset.productLink].classList.add('active')
        document.querySelector('.product-controls__tab.active').classList.remove('active')
        e.target.classList.add('active')
    })
</script>