<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<div class="product-faq__container">
    <div class="product-faq__links">
        <a href="<?= $block->escapeUrl('#') ?>" class="product-faq__link">
            <span>Product Support</span>
        </a>
        <a href="<?= $block->escapeUrl('#') ?>" class="product-faq__link">
            <span>FAQ</span>
        </a>
        <a href="<?= $block->escapeUrl('#') ?>" class="product-faq__link">
            <span>Our Buyers Guide</span>
        </a>
    </div>
    
       
    </div>
   
</div>