<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<ul class="product-controls__tabs" data-product-controls>
  <li><a href="<?= $block->escapeUrl('#') ?>"
      class="product-controls__tab active" data-product-link='0'><?= __("About
      products") ?></a></li>
  <li><a href="<?= $block->escapeUrl('#') ?>" class="product-controls__tab"
      data-product-link='1'><?= __("Details") ?></a></li>
  <li><a href="<?= $block->escapeUrl('#') ?>" class="product-controls__tab"
      data-product-link='2'><?= __("Specs") ?></a></li>
</ul>
