<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>




    <ul class="product-controls__tabs" data-product-controls>
        <li><a href="<?= $block->escapeUrl('#') ?>" class="product-controls__tab active" data-product-link='0'>About products</a></li>
        <li><a href="<?= $block->escapeUrl('#') ?>" class="product-controls__tab" data-product-link='1'>Details</a></li>
        <li><a href="<?= $block->escapeUrl('#') ?>" class="product-controls__tab" data-product-link='2'>Specs</a></li>
    </ul>


