<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View\Description*/
?>

<?php

/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $this->getData('outputHelper');
?>


    
    <p class="product-short-description"><?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute($block->getProduct(), $block->getProduct()->getDescription(), 'description')?></p>
    <p><?= $block->getProduct()->getShortDescription() ?> </p>
  
   



