<div class="copyright">
  <div class="copyright__wrap">
    <div class="copyright__socials">
      <a id="copyright__link" href="facebook.com">
        <img src='<?php echo $this->getViewFileUrl('images/fb-logo.svg'); ?>'
          alt="facebook logo">
      </a>
      <a id="copyright__link" href="instagram.com">
        <img src='<?php echo $this->getViewFileUrl('images/inst-logo.svg'); ?>'
          alt="instagram logo">
      </a>
    </div>
    <div class="copyright__payment">
      <a id="copyright__link" href="paypal.com">
        <img src='<?php echo $this->getViewFileUrl('images/paypal.svg'); ?>'
          alt="paypal logo">
      </a>
      <a id="copyright__link" href="visa.com">
        <img src='<?php echo $this->getViewFileUrl('images/visa.svg'); ?>'
          alt="visa logo">
      </a>
      <a id="copyright__link" href="maestro.com">
        <img src='<?php echo $this->getViewFileUrl('images/maestro.svg'); ?>'
          alt="maestro logo">
      </a>
      <a id="copyright__link" href="discover.com">
        <img src='<?php echo $this->getViewFileUrl('images/discover.svg'); ?>'
          alt="discover logo">
      </a>
      <a id="copyright__link" href="americanexpress.com">
        <img
          src='<?php echo $this->getViewFileUrl('images/american-express.svg'); ?>'
          alt="american-express logo">
      </a>
    </div>
    <small class="copyright__text">
      <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
    </small>
  </div>

</div>