<div class="footer-col-links">
  <div data-role="collapsible" class='collap'>
    <div data-role="trigger">
      <h3 class="footer__title">Information</h3>
      <div class="footer__caret">
      </div>
    </div>
  </div>
  <ul class="footer__list" data-role="content">
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("About Us") ?></a></li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("About Zip") ?></a></li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("Privacy Policy") ?></a>
    </li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("Search") ?></a></li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("Terms") ?></a></li>
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __("Orders and Returns") ?></a>
    </li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("Contact Us") ?></a>
    </li>
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __("Advanced Search") ?></a>
    </li>
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __("Newsletter Subscription") ?></a>
    </li>
  </ul>
</div>
<div class="footer-col-links">
  <div data-role="collapsible" class='collap'>
    <div data-role="trigger">
      <h3 class="footer__title"><?= __('PC Parts') ?></h3>
      <div class="footer__caret">
      </div>
    </div>
  </div>
  <ul class="footer__list" data-role="content">
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __('CPUS') ?></a></li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __('Add On Cards') ?></a>
    </li>
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __('Hard Drives (Internal)') ?></a>
    </li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __('Graphic Cards') ?></a>
    </li>
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __('Keyboards / Mice') ?></a>
    </li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __('Cases / Power Supplies /
        Cooling') ?></a></li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __('RAM (Memory)') ?></a>
    </li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __('Software') ?></a></li>
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __('Speakers / Headsets') ?></a>
    </li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __('Motherboards') ?></a>
    </li>
  </ul>
</div>
<div class="footer-col-links">
  <div data-role="collapsible" class='collap'>
    <div data-role="trigger">
      <h3 class="footer__title"><?= __('Desktop PCs') ?></h3>
      <div class="footer__caret">
      </div>
    </div>
  </div>
  <ul class="footer__list" data-role="content">
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("Custom PCs") ?></a>
    </li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("Servers") ?></a></li>
    <li>
      <ahref="<?= $block->escapeUrl('#'); ?>">
        <?= __("MSI All-In-One PCs") ?></a>
    </li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("HP/Compaq PCs") ?></a>
    </li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("ASUS PCs") ?></a></li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("Tecs PCs") ?></a></li>
  </ul>
</div>
<div class="footer-col-links">
  <div data-role="collapsible" class='collap'>
    <div data-role="trigger">
      <h3 class="footer__title"><?= __("Laptops") ?></h3>
      <div class="footer__caret">
      </div>
    </div>
  </div>
  <ul class="footer__list" data-role="content">
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __("Everyday Use Notebooks") ?></a>
    </li>
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __("MSI Workstation Series") ?></a>
    </li>
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __("MSI Prestige Series") ?></a>
    </li>
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __("Tablets and Pads") ?></a>
    </li>
    <li><a href="<?= $block->escapeUrl('#'); ?>"><?= __("Netbooks") ?></a></li>
    <li><a
        href="<?= $block->escapeUrl('#'); ?>"><?= __("Infinity Gaming Notebooks") ?></a>
    </li>
  </ul>
</div>
<div class="footer-col-links">
  <div data-role="collapsible" class='collap'>
    <div data-role="trigger">
      <h3 class="footer__title"><?= __("Address") ?></h3>
      <div class="footer__caret">
      </div>
    </div>
  </div>
  <ul class="footer__list" data-role="content">
    <li><?= __("Address") ?>: 1234 Street Adress City Address, 1234</li>
    <li><?= __("Phones") ?>:<a href="tel:(00) 1234 5678">(00) 1234 5678</a></li>
    <li><?= __("We are open") ?>: Monday-Thursday: 9:00 AM - 5:30 PM</li>
    <li>Friday: 9:00 AM - 6:00 PM</li>
    <li>Saturday: 11:00 AM - 5:00 PM</li>
    <li><?= __("E-mail") ?>:<a href="mailto:shop@email.com">shop@email.com</a>
    </li>
  </ul>
</div>

<script type="text/x-magento-init">
  {

        "*": {
            "Magento_Ui/js/core/app":{
                "components":{
                    "footer-accordion":{
                        "component":"Magento_Theme/js/footer-accordion"
                    }
                }
            }
       
            }
    }
    </script>