<div class="footer-col-links">
    <div data-role="collapsible" class='collap'>
        <div data-role="trigger">
            <h3 class="footer__title">Information</h3>
            <div class="footer__caret">

            </div>
        </div>
    </div>
    <ul class="footer__list" data-role="content">

        <li><a href="<?= $block->escapeUrl('#'); ?>">About Us</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">About Zip</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Privacy Policy</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Search</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Terms</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Orders and Returns</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Contact Us</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Advanced Search</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Newsletter Subscription</a></li>
    </ul>
</div>

<div class="footer-col-links">
    <div data-role="collapsible" class='collap'>
        <div data-role="trigger">
            <h3 class="footer__title">PC Parts</h3>
            <div class="footer__caret">

            </div>
        </div>
    </div>
    <ul class="footer__list" data-role="content">

        <li><a href="<?= $block->escapeUrl('#'); ?>">CPUS</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Add On Cards</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Hard Drives (Internal)</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Graphic Cards</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Keyboards / Mice</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Cases / Power Supplies / Cooling</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">RAM (Memory)</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Software</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Speakers / Headsets</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Motherboards</a></li>
    </ul>
</div>

<div class="footer-col-links">
    <div data-role="collapsible" class='collap'>
        <div data-role="trigger">
            <h3 class="footer__title">Desktop PCs</h3>
            <div class="footer__caret">

            </div>
        </div>
    </div>
    <ul class="footer__list" data-role="content">

        <li><a href="<?= $block->escapeUrl('#'); ?>">Custom PCs</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Servers</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">MSI All-In-One PCs</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">HP/Compaq PCs</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">ASUS PCs</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Tecs PCs</a></li>

    </ul>
</div>








<div class="footer-col-links">
    <div data-role="collapsible" class='collap'>
        <div data-role="trigger">
            <h3 class="footer__title">Laptops</h3>
            <div class="footer__caret">

            </div>
        </div>
    </div>
    <ul class="footer__list" data-role="content">

        <li><a href="<?= $block->escapeUrl('#'); ?>">Everyday Use Notebooks</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">MSI Workstation Series</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">MSI Prestige Series</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Tablets and Pads</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Netbooks</a></li>
        <li><a href="<?= $block->escapeUrl('#'); ?>">Infinity Gaming Notebooks</a></li>
    </ul>
</div>

<div class="footer-col-links">
    <div data-role="collapsible" class='collap'>
        <div data-role="trigger">
            <h3 class="footer__title">Address</h3>
            <div class="footer__caret">

            </div>
        </div>
    </div>
    <ul class="footer__list" data-role="content">

        <li>Address: 1234 Street Adress City Address, 1234</li>
        <li>Phones:<a href="tel:(00) 1234 5678">(00) 1234 5678</a></li>
        <li>We are open: Monday-Thursday: 9:00 AM - 5:30 PM</li>
        <li>Friday: 9:00 AM - 6:00 PM</li>
        <li>Saturday: 11:00 AM - 5:00 PM</li>
        <li>E-mail:<a href="mailto:shop@email.com">shop@email.com</a></li>

    </ul>
</div>



<script type="text/x-magento-init">
    {

        "*": {
            "Magento_Ui/js/core/app":{
                "components":{
                    "footer-accordion":{
                        "component":"Magento_Theme/js/footer-accordion"
                    }
                }
            }
       
            }
    }
    </script>