<div class='footer-head__wrap'>
    <h2 class='footer-head__title'>sign up to our newsletter.</h2>
    <p class='footer-head__subtitle'>Be the first to hear about the latest offers.</p>
</div>



<style>
    .footer-head__wrap{
        display:flex;
        flex-direction:column;
        gap:0.5rem;
    }

    .footer-head__title{
        text-transform:capitalize;
        font-family: Poppins;
font-style: normal;
font-weight: bold;
font-size: clamp(1.8rem, 4vw - 1.25rem, 3.8rem);
color:white;
margin: 0;

    }

    .footer-head__subtitle{
        font-weight: 300;
font-size: clamp(1.2rem, 0.46vw + 1rem, 1.6rem);
color:white;
    }
</style>