<div class="review__wrap">
  <div class="review__slider">
    <div class="review__slides">
      <div class="review__slide">
        <div class="review__content">
          <div class="review__parentesis">&lsquo;&rsquo;</div>
          <div class="review__quote">My first order arrived today in perfect
            condition. From the time I sent a question about the item to making
            the purchase, to the shipping and now the delivery, your company,
            Tecs, has stayed in touch. Such great service. I look forward to
            shopping on your site in the future and would highly recommend it.
          </div>
          <div class="review__author">- Tama Brown</div>
        </div>
      </div>
      <div class="review__slide">
        <div class="review__content">
          <div class="review__parentesis">&lsquo;&rsquo;</div>
          <div class="review__quote">My first order arrived today in perfect
            condition. From the time I sent a question about the item to making
            the purchase, to the shipping and now the delivery, your company,
            Tecs, has stayed in touch. Such great service. I look forward to
            shopping on your site in the future and would highly recommend it.
          </div>
          <div class="review__author">- Tama Brown</div>
        </div>
      </div>
    </div>
    <div class="review__controls">
      <button class="review__btn"><?= __("Leave Us A Review") ?></button>
      <div class="review__control">
      </div>
    </div>

  </div>
</div>

<script type="text/x-magento-init">
  {
        "*": {
            "Magento_Ui/js/core/app":{
                "components":{
                    "review-slider":{
                        "component":"Magento_Theme/js/review-slider"
                    }
                }
            }
       
            }
    }
    </script>