<?php
/**
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)) : ?>
<div class="filter-current">
  <ol class="items">
    <?php foreach ($_filters as $_filter) : ?>
    <li class="item">
      <span
        class="filter-value"><?= $block->escapeHtml($block->stripTags($_filter->getLabel())) ?></span>
      <span class="toolbar-number"><?= $block->getTotalNum() ?></span>
      <?php $clearLinkUrl = $_filter->getClearLinkUrl();
                    $currentFilterName = $block->escapeHtmlAttr(__($_filter->getName()) . " " . $block->stripTags($_filter->getLabel()));
                    if ($clearLinkUrl) : ?>
      <a class="action previous"
        href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
        title="<?= $block->escapeHtmlAttr(__('Previous')) ?>">
        <span><?= $block->escapeHtml(__('Previous')) ?></span>
      </a>
      <a class="action remove"
        title="<?= $block->escapeHtmlAttr($_filter->getFilter()->getClearLinkText()) ?>"
        href="<?= $block->escapeUrl($clearLinkUrl) ?>">
        <span><?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
      </a>
      <?php else : ?>
      <a class="action remove"
        href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
        title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Remove')) . " " . $currentFilterName ?>">
        <span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
      </a>
      <?php endif; ?>
    </li>
    <?php endforeach; ?>
    <li class="item">
      <div class="block-actions filter-actions">
        <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>"
          class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
      </div>
    </li>
  </ol>
</div>
<?php endif; ?>
