<div data-mage-init='{"tabs":{"openedState":"active"}}'>
  <nav class="navigation" data-action="navigation">
    <ul id="menu"
      data-mage-init='{"menu":{"responsive":true, "expanded":true, "delay": 200, "position":{"my":"left top","at":"left+10 top+30"}}}'>
      <li class="level0 level-top ui-menu-item"> <?= __("Toys") ?></li>
      <li class="level0 level-top parent ui-menu-item"> <?= __("Electronics") ?>
        <ul
          class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
          <li class="ui-menu-item"><a href="#">
              <?= __("Home Entertainment") ?></a></li>
          <li class="ui-menu-item"><a href="#"> <?= __("Routers") ?></a></li>
        </ul>
      </li>
      <li class="level0 level-top ui-menu-item"> <?= __("Music") ?>
        <ul
          class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
          <li class="ui-menu-item">
            <a href="#"> <?= __("Alternative") ?></a>
          </li>
          <li class="ui-menu-item">
            <a href="#"> <?= __("Classic") ?></a>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</div>
